### ISSUE TITLE
Be carefull with dependencies

### ISSUE THREAD

**Issue by woutervanwijk** [zino-app/graphql-flutter#925]
When upgrading graphql from 5.0.0-nullsafety.5 to 5.0.0, connectivity_plus_macos 0.0.1 is included. This leads to the  build error below (with no other changes in packages or code). 

While connectivity-checking seems a nice addition to graphql_flutter, I doubt if it belongs in this package, especially because it creates an extra dependency. Shouldn't this be done in the app?

```
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
/Users/code/test/macos/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Wpointer-to-int-cast]
                             NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                              ^~~~~~~~~~~~~~~~~~~
1 warning generated.
/Users/code/test/build/macos/Build/Products/Debug/connectivity_plus_macos/connectivity_plus_macos.framework/Headers/connectivity_plus_macos-Swift.h:216:1: error: 'ConnectivityPlugin' has different definitions in different modules; first difference is definition in module 'connectivity_plus_macos.Swift' found return type is 'void'
+ (void)registerWithRegistrar:(id <FlutterPluginRegistrar> _Nonnull)registrar;
^
/Users/code/test/build/macos/Build/Products/Debug/connectivity_macos/connectivity_macos.framework/Headers/connectivity_macos-Swift.h:216:1: note: but in 'connectivity_macos.Swift' found different return type 'instancetype _Nonnull' (aka 'id')
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
^
/Users/code/test/macos/Flutter/GeneratedPluginRegistrant.swift:21:3: error: ambiguous use of 'register(with:)'
  ConnectivityPlugin.register(with: registry.registrar(forPlugin: "ConnectivityPlugin"))
  ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.2.0/macos/Classes/ConnectivityPlugin.swift:20:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {

                     ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.2/macos/Classes/ConnectivityPlugin.swift:24:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {

                     ^
/Users/code/test/macos/Flutter/GeneratedPluginRegistrant.swift:22:3: error: ambiguous use of 'register(with:)'
  ConnectivityPlugin.register(with: registry.registrar(forPlugin: "ConnectivityPlugin"))
  ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.2.0/macos/Classes/ConnectivityPlugin.swift:20:22: note: found this candidate

  public static func register(with registrar: FlutterPluginRegistrar) {
                     ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.2/macos/Classes/ConnectivityPlugin.swift:24:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {
                     ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
```

**Comment by mhadaily** [comment]
We have released a new version `1.0.5` for `connectivity_plus` please consider upgrading your depecenies.

**Comment by woutervanwijk** [comment]
Great!

**Comment by ol88** [comment]
I updated the PR with 1.0.5 but as you know the lack of active maintainer means it may take some time before this is merged. You might need to fork and do the change manually in the meantime.

**Comment by woutervanwijk** [comment]
I still have this issue. Is it really necessary to use the connectivity(_plus) dependency in graphql_flutter? Shouldn't an app handle the connectivity itself?

**Comment by vincenzopalazzo** [comment]
Fixed with https://github.com/zino-app/graphql-flutter/pull/978

Thanks
