### ISSUE TITLE
Upgrading graphql to 3.0.2 breaks subscriptions

### ISSUE THREAD

**Issue by gtupak** [zino-app/graphql-flutter#658]
**Describe the bug**
The subscriptions worked fine with package version `3.0.1-beta.2` of `graphql`. Upgrading to `3.0.2` made my subscriptions throw the following error:

```
Connecting to VM Service at ws://localhost:1025/ws[38;5;244m[log] [39;49mLogged in!
flutter: Connecting to websocket: ws://<serverURL>
flutter: Connected to websocket.
flutter: There was an error causing connection lost: Converting object to an encodable object failed: Instance of 'InitOperation'
flutter: Disconnected from websocket.
flutter: Scheduling to connect in 5 seconds...
flutter: Caught error: NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (GraphQLSocketMessage) => bool)
flutter: #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      SocketClient.subscribe.<anonymous closure>.<anonymous closure> 
package:graphql/src/socket_client.dart:284
[...]
```

The debug console points the issue at file `graphql-3.0.2/lib/src/socket_client.dart:284`

**To Reproduce**
I have the following scenario:

```dart
String serverURL = "<serverURL>",
String subscriptionURL = "<subscriptionURL>";

HttpClient httpClient = HttpClient();

final httpLink = HttpLink(
  uri: serverURL,
  httpClient: ioClient,
);

final authLink = AuthLink(
  getToken: () async => 'Bearer $_token',
);

final webSocketLink = WebSocketLink(
  url: subscriptionURL,
  config: SocketClientConfig(
    autoReconnect: true,
    inactivityTimeout: Duration(minutes: 5),
    initPayload: () => {'api-key': _token},
  ),
);

final link = Link.from([authLink, httpLink, webSocketLink]);

return GraphQLClient(
  cache: NormalizedInMemoryCache(
    dataIdFromObject: typenameDataIdFromObject,
  ),
  link: link,
);
```

And later on, create my subscription like so:

```dart
Stream<Project> subscribeProject(String projectId) async* {
  final subOperation = Operation(
    documentNode: gql(Subscriptions.SubscribeProject),
    variables: {'id': projectId},
  );

  await for (FetchResult result in gqlClient.subscribe(subOperation)) {
    try {
      yield Project.fromJson(result.data['project']);
    } catch (e) {
      debugPrint(e);
    }
  }
}
```

**Expected behavior**
Do not see an error stacktrace.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android SDK file not found: adb.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by micimize** [comment]
`initPayload` should be a literal value (`{'api-key': _token}`) and not a callback (`() => {'api-key': _token}`) which is why this is failing to serialize initially.

Going through the diff (even against master) I don't think there's a particular change causing this: https://github.com/zino-app/graphql-flutter/compare/v3.0.1-beta.2...master. The error could certainly be clearer though

**Comment by RodolfoSilva** [comment]
@micimize Has any example how to use `initialPayload` with async data? Like `AuthLink` with `getToken`?

**Comment by RodolfoSilva** [comment]
@micimize Has any example how to use `initialPayload` with async data? Like `AuthLink` with `getToken`? 

Before version 4.0.0-alpha.0, I used it like this:

```dart
final WebSocketLink websocketLink = WebSocketLink(
  subscriptionUri,
  config: SocketClientConfig(
    autoReconnect: true,
    inactivityTimeout: Duration(seconds: 30),
    initPayload: () async {
      final String token = await Hive.box('auth').get('token');

      if (token == null || token.isEmpty) return {};

      return {
        "headers": {"Authorization": 'Bearer ' + token}
      };
    },
  ),
);
```

**Comment by micimize** [comment]
@RodolfoSilva sorry – amended my comment above. Looks like we need to apply the async `initialPayload` handling logic from `beta` to [`gql_websocket_link` ](https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/lib/src/link.dart#L154)

**Comment by RodolfoSilva** [comment]
Thanks @micimize

**Comment by RodolfoSilva** [comment]
@micimize I send a PR. (https://github.com/gql-dart/gql/pull/122)

**Comment by NotHolst** [comment]
Any idea when this fix will make its way into master?

**Comment by RodolfoSilva** [comment]
@NotHolst,
I think @micimize is waiting @klavs

**Comment by micimize** [comment]
`4.0.0-alpha.6` revived the old `WebSocketLink` and should resolve this
