### ISSUE TITLE
Not compatible with mapbox_gl

### ISSUE THREAD

**Issue by ecerroni** [zino-app/graphql-flutter#624]
**Describe the bug**
This package is not working with `mapbox_gl 0.0.5`

**To Reproduce**
As soon as you add `mapbox_gl: ^0.0.5` to `pubspec.yaml` the graphql package stop working properly.

**Expected behavior**
I would expect `graphql-flutter` to not throw exceptions

**Screenshots**
![image](https://user-images.githubusercontent.com/11174327/80961414-3d276d80-8e0b-11ea-99a7-d09137a6d944.png)

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
not tested

**Additional context**
The error that is thrown
```
I/flutter (10983): ClientException: Unhandled Failure NoSuchMethodError: The method 'read' was called on null.
I/flutter (10983): Receiver: null
I/flutter (10983): Tried calling: read("query _checkAuth {\n  _checkAuth\n}|{}|_checkAuth")
I/flutter (10983): IS LOADING
I/flutter (10983): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10983): The following LocaleDataException was thrown building StreamBuilder<QueryResult>-[<'query _checkAuth
I/flutter (10983): {
I/flutter (10983):   _checkAuth
I/flutter (10983): }|{}|_checkAuth'>](dirty, state: _StreamBuilderBaseState<QueryResult,
I/flutter (10983): AsyncSnapshot<QueryResult>>#8e4a4):
I/flutter (10983): Locale data has not been initialized, call initializeDateFormatting(<locale>).

```
Class code snippet:
```
...
 @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Query(
          options: QueryOptions(
            documentNode: Queries.auth),
          builder: (QueryResult result, { VoidCallback refetch, FetchMore fetchMore }) {
            if(result.hasException) print('ERROR: ${result.exception}');

            if (result.loading) {
              // return Text('Loading');
            }
            // it can be either Map or List
            // List repositories = result.data['viewer']['repositories']['nodes'];
            return MapWidget();
      },
    )),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  ....
```

**Comment by ecerroni** [comment]
We've switched to Leaflet using Mapbox tiles and there is no more issue with that.

However, it still worth looking into it imho.

**Comment by vasilich6107** [comment]
Added `mapbox_gl` to my project as mentioned in `To Reproduce` - everything works fine.
May be there are some more steps to mention?
